config/routes.rb
Rails.application.routes.draw do
  # devise_scope :customers do
  #   get 'customers/sign_up' => 'devise/registrations#new'
  # end
  devise_for :customers, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }

  # get "todolists/new"
  # get "/top" => "homes#top"
  # post "todolists" => "todolists#create"
  # get "todolists" => "todolists#index"
  resources :todolists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController

  def new
    @list = List.new()
  end

  def create
    list = List.new(list_params)
    list.save
    redirect_to todolist_path(list), notice: "作成に成功しました"
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def list_params
    params.require(:list).permit(:title, :body)
  end

  def set_params
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/homes/top.html.erb
トップページです

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/edit.html.erb
<%= form_with model:@list,local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit "投稿" %>
<% end %>

app/views/todolists/index.html.erb
一覧画面
<% @lists.each do |list| %>
  <% binding.pry %>
  <div>
  タイトル:<%= list.title %>
  本文:<%= list.body %>
  </div>
<% end%>

<%= link_to "新規投稿", new_todolist_path %>
<%=%>

app/views/todolists/new.html.erb
<%#= form_with model: @list,local:true do |f| %>
<%= form_with model:@list, url: todolists_path, method: :post, local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit "投稿" %>
<% end %>

app/views/todolists/show.html.erb
<p>タイトル</p>
<%= @list.title %>
<p>本文</p>
<%= @list.body %>